@startuml

title __C's Class Diagram__\n

  package hu.bme.mit.mcmec.c2xta {
    package hu.bme.mit.mcmec.c2xta.c {
      class MyCVisitor {
          - atomicsList : List<String>
          - mutexList : List<String>
          - cndList : List<String>
          - threadStateLUT : Map<String, List<String>>
          - threadTransitionLUT : Map<String, Map<Integer, List<String>>>
          - currentThread : String
          - external : boolean
          - function : boolean
          - atomic : boolean
          - mutex : boolean
          - cnd : boolean
          {static} - atomicQualifier : String
          {static} - mutexSpecifier : String
          {static} - conditionSpecifier : String
          {static} - atomic_load : String
          {static} - atomic_store : String
          {static} - cnd_wait : String
          {static} - cnd_signal : String
          {static} - cnd_broadcast : String
          {static} - mtx_lock : String
          {static} - mtx_unlock : String
          {static} - thrd_create : String
          {static} - thrd_join : String
          {static} - _return : String
          - cnt : int
          {static} - memory_mode : String
          + MyCVisitor()
          + toString()
          + visitExternalDeclaration()
          + visitTypeQualifier()
          + visitTypeSpecifier()
          + visitFunctionDefinition()
          + visitBlockItem()
          + visitDirectDeclarator()
      }
    }
  }
  

  MyCVisitor -up-|> CBaseVisitor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
