@startuml

title __MCMEC's Class Diagram__\n

  package hu.bme.mit.mcmec {
    class Mcmec {
        {static} - MODE_ALL : String
        {static} - MODE_LITMUS2ISSUES : String
        {static} - MODE_C2XTA : String
        {static} - MODE_XTA2QUERY : String
        {static} - MODE_QUERY2RESULT : String
        {static} - MODE_ALL_MITIGATION : String
        {static} - MODE_GUI : String
        {static} - ISSUES_FILE_NAME : String
        {static} - XTA_FILE_NAME : String
        {static} - QUERY_FILE_NAME : String
        {static} - QUERY2_FILE_NAME : String
        {static} - LITMUS_FOLDER : String
        {static} - UPPAAL_HOME : String
        {static} - SOURCE_FILE : String
        {static} - MODE : String
        {static} - PARAM_SHORT_ISSUES : String
        {static} - PARAM_SHORT_LITMUS_FOLDER : String
        {static} - PARAM_SHORT_XTA : String
        {static} - PARAM_SHORT_QUERY : String
        {static} - PARAM_SHORT_QUERY2 : String
        {static} - PARAM_SHORT_UPPAAL_HOME : String
        {static} - PARAM_SHORT_SOURCE_FILE : String
        {static} - PARAM_SHORT_MODE : String
        {static} - PARAM_LONG_ISSUES : String
        {static} - PARAM_LONG_LITMUS_FOLDER : String
        {static} - PARAM_LONG_XTA : String
        {static} - PARAM_LONG_QUERY : String
        {static} - PARAM_LONG_QUERY2 : String
        {static} - PARAM_LONG_UPPAAL_HOME : String
        {static} - PARAM_LONG_SOURCE_FILE : String
        {static} - PARAM_LONG_MODE : String
        {static} + main()
        {static} + run()
        {static} + getUppaalHome()
        {static} + getIssuesFileName()
        {static} + getQueryFileName()
        {static} + getXtaFileName()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
