@startuml

title __SRC's Component Diagram__\n

  component "mcmec" {
        [hu.bme.mit.mcmec_main]
    component "hu.bme.mit.mcmec_main" {
          [hu.bme.mit.mcmec]
      component "hu.bme.mit.mcmec" {
            [hu.bme.mit.mcmec.mitigationgenerator]
            [hu.bme.mit.mcmec.tricheckparser]
            [hu.bme.mit.mcmec.model2uppaal]
            [hu.bme.mit.mcmec.verifier]
            [hu.bme.mit.mcmec.c2xta]
        component "hu.bme.mit.mcmec.mitigationgenerator" {
              [hu.bme.mit.mcmec.mitigationgenerator_main]
        }


        component "hu.bme.mit.mcmec.tricheckparser" {
              [hu.bme.mit.mcmec.tricheckparser_main]
        }


        component "hu.bme.mit.mcmec.model2uppaal" {
              [hu.bme.mit.mcmec.model2uppaal_main]
        }


        component "hu.bme.mit.mcmec.verifier" {
              [hu.bme.mit.mcmec.verifier_main]
        }


        component "hu.bme.mit.mcmec.c2xta" {
              [hu.bme.mit.mcmec.c2xta_main]
        }


      }


    }


  }


  [hu.bme.mit.mcmec_main] --> [hu.bme.mit.mcmec.c2xta_main]
  [hu.bme.mit.mcmec_main] --> [hu.bme.mit.mcmec.model2uppaal_main]
  [hu.bme.mit.mcmec_main] --> [hu.bme.mit.mcmec.tricheckparser_main]
  [hu.bme.mit.mcmec_main] --> [hu.bme.mit.mcmec.verifier_main]
  [hu.bme.mit.mcmec_main] --> [hu.bme.mit.mcmec.mitigationgenerator_main]
  [mcmec_main] --> [hu.bme.mit.mcmec_main]
  [mcmec_main] --> [hu.bme.mit.mcmec.mitigationgenerator_main]
  [mcmec_main] --> [hu.bme.mit.mcmec.c2xta_main]
  [mcmec_main] --> [hu.bme.mit.mcmec.model2uppaal_main]
  [mcmec_main] --> [hu.bme.mit.mcmec.tricheckparser_main]
  [mcmec_main] --> [hu.bme.mit.mcmec.verifier_main]


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
